export const brand = {
	ul1: [
		{ to: '', text: 'Все бренды' },
		{ to: '', text: 'adidas Originals' },
		{ to: '', text: 'Alpha Indistries' },
		{ to: '', text: 'Book Publishers' },
		{ to: '', text: 'C.P. Company' },
		{ to: '', text: 'Calvin Klein Jeans' },
		{ to: '', text: 'Canada Goose' },
		{ to: '', text: 'CASIO' },
		{ to: '', text: 'Champion Reverse Weave' },
		{ to: '', text: 'Comme des Garcons SHIRT' },
		{ to: '', text: 'Daniel Wellington' },
		{ to: '', text: 'Edwin' },
		{ to: '', text: 'Evisu' },
		{ to: '', text: 'Hackett' },
	],
	ul2: [
		{ to: '', text: 'Helly Hansen' },
		{ to: '', text: 'Lacoste' },
		{ to: '', text: 'Levis' },
		{ to: '', text: 'Ligne Blanche' },
		{ to: '', text: 'MA.Strum' },
		{ to: '', text: 'maharishi' },
		{ to: '', text: 'Maison Kitsune' },
		{ to: '', text: 'MARKET' },
		{ to: '', text: 'Master-piece' },
		{ to: '', text: 'Medicom Toy' },
		{ to: '', text: 'MKI Miyuki-Zoku' },
		{ to: '', text: 'MSGM' },
		{ to: '', text: 'Napapijri' },
	],
	ul3: [
		{ to: '', text: 'Native Union' },
		{ to: '', text: 'New Balance' },
		{ to: '', text: 'Nike' },
		{ to: '', text: 'Norse Projects' },
		{ to: '', text: 'Oakley' },
		{ to: '', text: 'Peaceful Hooligan' },
		{ to: '', text: 'Polo Ralph Lauren' },
		{ to: '', text: 'Porter-Yoshida & Co' },
		{ to: '', text: 'Puma' },
		{ to: '', text: 'RAINS' },
		{ to: '', text: 'Ray-Ban' },
		{ to: '', text: 'Reebok' },
		{ to: '', text: 'Ripndip' },
	],
	ul4: [
		{ to: '', text: 'Sandqvist' },
		{ to: '', text: 'Seiko' },
		{ to: '', text: 'Stone Island' },
		{ to: '', text: 'The North Face' },
		{ to: '', text: 'thisisneverthat' },
		{ to: '', text: 'Timberland' },
		{ to: '', text: 'Timex' },
		{ to: '', text: 'Tommy Jeans' },
		{ to: '', text: 'uniform experiment' },
		{ to: '', text: 'Universal Works' },
		{ to: '', text: 'Vans' },
		{ to: '', text: 'Y-3' },
		{ to: '', text: 'YEEZY' },
	],
	img: [
		{
			text: 'The North Face',
			img: '/img/header-menu/tnf.jpg',
		},
		{ text: 'Lacoste', img: '/img/header-menu/lacoste.jpg' },
	],
}
