export const sale = {
	ul1: [
		{ to: '/brandlist', text: 'Все бренды' },
		{ to: '/sale/adidas-originals', text: 'adidas Originals' },
		{ to: '/sale/alpha-indistries', text: 'Alpha Indistries' },
		{ to: '/sale/cp-company', text: 'C.P. Company' },
		{ to: '/sale/calvin-klein-jeans', text: 'Calvin Klein Jeans' },
		{ to: '/sale/edwin', text: 'Edwin' },
		{ to: '/sale/helly-hansen', text: 'Helly Hansen' },
		{ to: '/sale/market', text: 'MARKET' },
		{ to: '/sale/napapijri', text: 'Napapijri' },
		{ to: '/sale/new-balance', text: 'New Balance' },
		{ to: '/sale/reebok', text: 'Reebok' },
		{ to: '/sale/thisisneverthat', text: 'thisisneverthat' },
		{ to: '/sale/vans', text: 'Vans' },
		{ to: '/sale/yeezy', text: 'YEEZY' },
	],
	ul2: [
		{ to: '/sale', text: 'Все категории' },
		{ to: '/sale/krossovki', text: 'Кроссовки' },
		{ to: '/sale/kurtki', text: 'Куртки' },
		{ to: '/sale/tolstovki', text: 'Толстовки' },
		{ to: '/sale/svitery', text: 'Свитеры' },
		{ to: '/sale/rubashki', text: 'Рубашки' },
		{ to: '/sale/longslivy', text: 'Лонгсливы' },
		{ to: '/sale/futbolki', text: 'Футболки' },
		{ to: '/sale/bryuki', text: 'Брюки' },
		{ to: '/sale/naruchnye-chasy', text: 'Наручные часы' },
		{ to: '/sale/shapki', text: 'Шапки' },
		{ to: '/sale/kepki', text: 'Кепки' },
		{ to: '/sale/noski', text: 'Носки' },
		{ to: '/sale/solncezashitnye-ochki', text: 'Солнцезащитные очки' },
	],
	img: [
		{
			to: '/sale/aksessuary',
			text: 'Аксессуары',
			img: '/img/header-menu/accessories.jpg',
		},
		{ to: '/sale/zhenskoe', text: 'Женское', img: '/img/header-menu/women.jpg' },
		{ to: '/sale/obuv', text: 'Обувь', img: '/img/header-menu/shoes.jpg' },
		{ to: '/sale/muzhskoe', text: 'Мужское', img: '/img/header-menu/men.jpg' },
	],
}
