export const wooman = {
	ul1: [
		{ to: '', text: 'Все бренды' },
		{ to: '', text: 'adidas Originals' },
		{ to: '', text: 'Canada Goose' },
		{ to: '', text: 'Champion Reverse Weave' },
		{ to: '', text: 'Levis' },
		{ to: '', text: 'Maison Kitsune' },
		{ to: '', text: 'MSGM' },
		{ to: '', text: 'Nike' },
		{ to: '', text: 'Saucony' },
		{ to: '', text: 'Puma' },
		{ to: '', text: 'Reebok' },
		{ to: '', text: 'New Balance' },
		{ to: '', text: 'Tommy Jeans' },
		{ to: '', text: 'Y-3' },
	],
	ul2: [
		{ to: '', text: 'Все категории' },
		{ to: '', text: 'Бомберы' },
		{ to: '', text: 'Брюки' },
		{ to: '', text: 'Джинсы' },
		{ to: '', text: 'Кроссовки' },
		{ to: '', text: 'Лонгсливы' },
		{ to: '', text: 'Олимпийки' },
		{ to: '', text: 'Парки' },
		{ to: '', text: 'Плащи' },
		{ to: '', text: 'Тапочки' },
		{ to: '', text: 'Толстовки' },
		{ to: '', text: 'Футболки' },
		{ to: '', text: 'Шорты' },
		{ to: '', text: 'Юбки' },
	],
	img: [
		{
			text: 'Обувь',
			img: '/img/header-menu/women_footwear.jpg',
		},
		{
			text: 'Одежда',
			img: '/img/header-menu/woomen_clothing.jpg',
		},
	],
}
