export const woman = {
	ul1: [
		{ to: '/brandlist/', text: 'Все бренды' },
		{ to: '/zhenskoe/adidas-originals/', text: 'adidas Originals' },
		{ to: '/zhenskoe/canada-goose/', text: 'Canada Goose' },
		{ to: '/zhenskoe/champion-reverse-weave/', text: 'Champion Reverse Weave' },
		{ to: '/zhenskoe/levis/', text: 'Levis' },
		{ to: '/zhenskoe/maison-kitsune/', text: 'Maison Kitsune' },
		{ to: '/zhenskoe/msgm/', text: 'MSGM' },
		{ to: '/zhenskoe/nike/', text: 'Nike' },
		{ to: '/zhenskoe/saucony/', text: 'Saucony' },
		{ to: '/zhenskoe/puma/', text: 'Puma' },
		{ to: '/zhenskoe/reebok/', text: 'Reebok' },
		{ to: '/zhenskoe/new-balance/', text: 'New Balance' },
		{ to: '/zhenskoe/tommy-jeans/', text: 'Tommy Jeans' },
		{ to: '/zhenskoe/y-3/', text: 'Y-3' },
	],
	ul2: [
		{ to: '/zhenskoe/', text: 'Все категории' },
		{ to: '/zhenskoe/bombery/', text: 'Бомберы' },
		{ to: '/zhenskoe/bryuki/', text: 'Брюки' },
		{ to: '/zhenskoe/dzhinsy/', text: 'Джинсы' },
		{ to: '/zhenskoe/krossovki/', text: 'Кроссовки' },
		{ to: '/zhenskoe/longslivy/', text: 'Лонгсливы' },
		{ to: '/zhenskoe/olimpijki/', text: 'Олимпийки' },
		{ to: '/zhenskoe/parki/', text: 'Парки' },
		{ to: '/zhenskoe/plashi/', text: 'Плащи' },
		{ to: '/zhenskoe/tapochki/', text: 'Тапочки' },
		{ to: '/zhenskoe/tolstovki/', text: 'Толстовки' },
		{ to: '/zhenskoe/futbolki/', text: 'Футболки' },
		{ to: '/zhenskoe/shorty/', text: 'Шорты' },
		{ to: '/zhenskoe/yubki/', text: 'Юбки' },
	],
	img: [
		{
			to: '/zhenskoe/obuv/',
			text: 'Обувь',
			img: '/img/header-menu/women_footwear.jpg',
		},
		{ to: '/zhenskoe/odezhda/', text: 'Одежда', img: '/img/header-menu/woomen_clothing.jpg' },
	],
}
