export const man = {
	ul1: [
		{ to: '/brandlist', text: 'Все бренды' },
		{ to: '/muzhskoe/adidas-originals', text: 'adidas Originals' },
		{ to: '/muzhskoe/cp-company', text: 'C.P. Company' },
		{ to: '/muzhskoe/comme-des-garcons-shirt', text: 'Comme des Garcons SHIRT' },
		{ to: '/muzhskoe/edwin', text: 'Edwin' },
		{ to: '/muzhskoe/lacoste', text: 'Lacoste' },
		{ to: '/muzhskoe/levis', text: 'Levis' },
		{ to: '/muzhskoe/nike', text: 'Nike' },
		{ to: '/muzhskoe/polo-ralph-lauren', text: 'Polo Ralph Lauren' },
		{ to: '/muzhskoe/ripndip', text: 'Ripndip' },
		{ to: '/muzhskoe/stone-island', text: 'Stone Island' },
		{ to: '/muzhskoe/the-north-face', text: 'The North Face' },
		{ to: '/muzhskoe/thisisneverthat', text: 'thisisneverthat' },
		{ to: '/muzhskoe/uniform-experiment', text: 'uniform experiment' },
	],
	ul2: [
		{ to: '/muzhskoe', text: 'Все категории' },
		{ to: '/muzhskoe/krossovki', text: 'Кроссовки' },
		{ to: '/muzhskoe/botinki', text: 'Ботинки' },
		{ to: '/muzhskoe/kedy', text: 'Кеды' },
		{ to: '/muzhskoe/kurtki', text: 'Куртки' },
		{ to: '/muzhskoe/svitera', text: 'Свитера' },
		{ to: '/muzhskoe/tolstovki', text: 'Толстовки' },
		{ to: '/muzhskoe/rubashki', text: 'Рубашки' },
		{ to: '/muzhskoe/longslivy', text: 'Лонгсливы' },
		{ to: '/muzhskoe/polo', text: 'Поло' },
		{ to: '/muzhskoe/futbolki', text: 'Футболки' },
		{ to: '/muzhskoe/dzhinsy', text: 'Джинсы' },
		{ to: '/muzhskoe/bryuki', text: 'Брюки' },
		{ to: '/muzhskoe/shorty', text: 'Шорты' },
	],
	img: [
		{
			to: '/muzhskoe/odezhda',
			text: 'Одежда',
			img: '/img/header-menu/mens_clothing.jpg',
		},
		{ to: '/muzhskoe/obuv', text: 'Обувь', img: '/img/header-menu/mens_footwear.jpg' },
	],
}
