export const access = {
	ul1: [
		{ to: '/brandlist/', text: 'Все бренды' },
		{ to: '/aksessuary/book-publishers/', text: 'Book Publishers' },
		{ to: '/aksessuary/bubble-gum/', text: 'Bubble Gum' },
		{ to: '/aksessuary/casio/', text: 'CASIO' },
		{ to: '/aksessuary/daniel-wellington/', text: 'Daniel Wellington' },
		{ to: '/aksessuary/ligne-blanche/', text: 'Ligne Blanche' },
		{ to: '/aksessuary/master-piece/', text: 'Master-piece' },
		{ to: '/aksessuary/native-union/', text: 'Native Union' },
		{ to: '/aksessuary/napapijri/', text: 'Napapijri' },
		{ to: '/aksessuary/polo-ralph-lauren/', text: 'Polo Ralph Lauren' },
		{ to: '/aksessuary/ray-ban/', text: 'Ray-Ban' },
		{ to: '/aksessuary/ripndip/', text: 'Ripndip' },
		{ to: '/aksessuary/timex/', text: 'Timex' },
		{ to: '/aksessuary/victorinox/', text: 'Victorinox' },
	],
	ul2: [
		{ to: '/aksessuary/', text: 'Все категории' },
		{ to: '/shapki/', text: 'Шапки' },
		{ to: '/sharfy/', text: 'Шарфы' },
		{ to: '/naruchnye-chasy/', text: 'Наручные часы' },
		{ to: '/solncezashitnye-ochki/', text: 'Солнцезащитные очки' },
		{ to: '/koshelki/', text: 'Кошельки' },
		{ to: '/remni/', text: 'Ремни' },
		{ to: '/kepki/', text: 'Кепки' },
		{ to: '/panamy/', text: 'Панамы' },
		{ to: '/nizhnee-bele/', text: 'Нижнее белье' },
		{ to: '/noski/', text: 'Носки' },
		{ to: '/sumki/', text: 'Сумки' },
		{ to: '/ryukzaki/', text: 'Рюкзаки' },
		{ to: '/posuda/', text: 'Посуда' },
	],
	img: [
		{
			to: '/solncezashitnye-ochki/',
			text: 'Солнцезащитные очки',
			img: '/img/header-menu/glasses.jpg',
		},
		{
			to: '/naruchnye-chasy/',
			text: 'Наручные часы',
			img: '/img/header-menu/watch.jpg',
		},
		{
			to: '/ryukzaki/',
			text: 'Рюкзаки',
			img: '/img/header-menu/bags.jpg',
		},
		{
			to: '/panamy/',
			text: 'Панамы',
			img: '/img/header-menu/panama.jpg',
		},
	],
}
