export const news = {
	ul1: [
		{ to: '/brandlist/', text: 'Все бренды' },
		{ to: '/adidas-originals/', text: 'adidas Originals' },
		{ to: '/cp-company/', text: 'C.P. Company' },
		{ to: '/calvin-klein-jeans/', text: 'Calvin Klein Jeans' },
		{ to: '/casio/', text: 'CASIO' },
		{ to: '/champion-reverse-weave/', text: 'Champion Reverse Weave' },
		{ to: '/levis/', text: 'Levis' },
		{ to: '/nike/', text: 'Nike' },
		{ to: '/polo-ralph-lauren/', text: 'Polo Ralph Lauren' },
		{ to: '/ripndip/', text: 'Ripndip' },
		{ to: '/the-north-face/', text: 'The North Face' },
		{ to: '/thisisneverthat/', text: 'thisisneverthat' },
		{ to: '/tommy-jeans/', text: 'Tommy Jeans' },
		{ to: '/y-3/', text: 'Y-3' },
	],
	ul2: [
		{ to: '/new/', text: 'Все категории' },
		{ to: '/kedy/', text: 'Кеды' },
		{ to: '/krossovki/', text: 'Кроссовки' },
		{ to: '/kurtki/', text: 'Куртки' },
		{ to: '/bryuki/', text: 'Брюки' },
		{ to: '/dzhinsy/', text: 'Джинсы' },
		{ to: '/longslivy/', text: 'Лонгсливы' },
		{ to: '/rubashki/', text: 'Рубашки' },
		{ to: '/svitera/', text: 'Свитера' },
		{ to: '/tolstovki/', text: 'Толстовки' },
		{ to: '/futbolki/', text: 'Футболки' },
		{ to: '/naruchnye-chasy/', text: 'Наручные часы' },
		{ to: '/ryukzaki/', text: 'Рюкзаки' },
		{ to: '/sumki/', text: 'Сумки' },
	],
	img: [
		{
			to: '/saucony/',
			text: 'Saucony',
			img: '/img/header-menu/saucony.jpg',
		},
		{ to: '/reebok/', text: 'Reebok', img: '/img/header-menu/reebok.jpg' },
		{ to: '/alpha-indistries/', text: 'Alpha Indistries', img: '/img/header-menu/alpha.jpg' },
		{ to: '/cp-company/', text: 'C.P. Company', img: '/img/header-menu/cp_company.jpg' },
	],
}
