export const brand = {
	ul1: [
		{ to: '/brandlist', text: 'Все бренды' },
		{ to: '/adidas-originals', text: 'adidas Originals' },
		{ to: '/alpha-indistries', text: 'Alpha Indistries' },
		{ to: '/book-publishers', text: 'Book Publishers' },
		{ to: '/cp-company', text: 'C.P. Company' },
		{ to: '/calvin-klein-jeans', text: 'Calvin Klein Jeans' },
		{ to: '/canada-goose', text: 'Canada Goose' },
		{ to: '/casio', text: 'CASIO' },
		{ to: '/champion-reverse-weave', text: 'Champion Reverse Weave' },
		{ to: '/comme-des-garcons-shirt', text: 'Comme des Garcons SHIRT' },
		{ to: '/daniel-wellington', text: 'Daniel Wellington' },
		{ to: '/edwin', text: 'Edwin' },
		{ to: '/evisu', text: 'Evisu' },
		{ to: '/hackett', text: 'Hackett' },
	],
	ul2: [
		{ to: '/helly-hansen', text: 'Helly Hansen' },
		{ to: '/lacoste', text: 'Lacoste' },
		{ to: '/levis', text: 'Levis' },
		{ to: '/ligne-blanche', text: 'Ligne Blanche' },
		{ to: '/mastrum', text: 'MA.Strum' },
		{ to: '/maharishi', text: 'maharishi' },
		{ to: '/maison-kitsune', text: 'Maison Kitsune' },
		{ to: '/market', text: 'MARKET' },
		{ to: '/master-piece', text: 'Master-piece' },
		{ to: '/medicom-toy', text: 'Medicom Toy' },
		{ to: '/mki-miyuki-zoku', text: 'MKI Miyuki-Zoku' },
		{ to: '/msgm', text: 'MSGM' },
		{ to: '/napapijri', text: 'Napapijri' },
	],
	ul3: [
		{ to: '/native-union', text: 'Native Union' },
		{ to: '/new-balance', text: 'New Balance' },
		{ to: '/nike', text: 'Nike' },
		{ to: '/norse-projects', text: 'Norse Projects' },
		{ to: '/oakley', text: 'Oakley' },
		{ to: '/peaceful-hooligan', text: 'Peaceful Hooligan' },
		{ to: '/polo-ralph-lauren', text: 'Polo Ralph Lauren' },
		{ to: '/porter-yoshida-co', text: 'Porter-Yoshida & Co' },
		{ to: '/puma', text: 'Puma' },
		{ to: '/rains', text: 'RAINS' },
		{ to: '/ray-ban', text: 'Ray-Ban' },
		{ to: '/reebok', text: 'Reebok' },
		{ to: '/ripndip', text: 'Ripndip' },
	],
	ul4: [
		{ to: '/sandqvist', text: 'Sandqvist' },
		{ to: '/seiko', text: 'Seiko' },
		{ to: '/stone-island', text: 'Stone Island' },
		{ to: '/the-north-face', text: 'The North Face' },
		{ to: '/thisisneverthat', text: 'thisisneverthat' },
		{ to: '/timberland', text: 'Timberland' },
		{ to: '/timex', text: 'Timex' },
		{ to: '/tommy-jeans', text: 'Tommy Jeans' },
		{ to: '/uniform-experiment', text: 'uniform experiment' },
		{ to: '/universal-works', text: 'Universal Works' },
		{ to: '/vans', text: 'Vans' },
		{ to: '/y-3', text: 'Y-3' },
		{ to: '/yeezy', text: 'YEEZY' },
	],
	img: [
		{
			to: '/the-north-face',
			text: 'The North Face',
			img: '/img/header-menu/tnf.jpg',
		},
		{ to: '/lacoste', text: 'Lacoste', img: '/img/header-menu/lacoste.jpg' },
	],
}
