export const access = {
	ul1: [
		{ to: '', text: 'Все бренды' },
		{ to: '', text: 'Book Publishers' },
		{ to: '', text: 'Bubble Gum' },
		{ to: '', text: 'CASIO' },
		{ to: '', text: 'Daniel Wellington' },
		{ to: '', text: 'Ligne Blanche' },
		{ to: '', text: 'Master-piece' },
		{ to: '', text: 'Native Union' },
		{ to: '', text: 'Napapijri' },
		{ to: '', text: 'Polo Ralph Lauren' },
		{ to: '', text: 'Ray-Ban' },
		{ to: '', text: 'Ripndip' },
		{ to: '', text: 'Timex' },
		{ to: '', text: 'Victorinox' },
	],
	ul2: [
		{ to: '', text: 'Все категории' },
		{ to: '', text: 'Шапки' },
		{ to: '', text: 'Шарфы' },
		{ to: '', text: 'Наручные часы' },
		{ to: '', text: 'Солнцезащитные очки' },
		{ to: '', text: 'Кошельки' },
		{ to: '', text: 'Ремни' },
		{ to: '', text: 'Кепки' },
		{ to: '', text: 'Панамы' },
		{ to: '', text: 'Нижнее белье' },
		{ to: '', text: 'Носки' },
		{ to: '', text: 'Сумки' },
		{ to: '', text: 'Рюкзаки' },
		{ to: '', text: 'Посуда' },
	],
	img: [
		{
			text: 'Солнцезащитные очки',
			img: '/img/header-menu/glasses.jpg',
		},
		{
			text: 'Наручные часы',
			img: '/img/header-menu/watch.jpg',
		},
		{
			text: 'Рюкзаки',
			img: '/img/header-menu/bags.jpg',
		},
		{
			text: 'Панамы',
			img: '/img/header-menu/panama.jpg',
		},
	],
}
