CREATE TABLE logo(id INT,brand VARCHAR(100),logo VARCHAR(100));
INSERT INTO logo (id,brand,logo) VALUES 
(1,'adidas Originals','/img/brand/adidas.svg'),
(2,'Alpha Indistries','/img/brand/alpha.svg'),
(3,'CASIO','/img/brand/casio.svg'),
(4,'Champion Reverse Weave','/img/brand/champion.svg'),
(5,'Saucony','/img/brand/saucony.svg'),
(6,'Victorinox','/img/brand/victorinox.svg'),
(7,'C.P. Company','/img/brand/cp.svg'),
(8,'uniform experiment','/img/brand/uniform-experiment.svg'),
(9,'Edwin','/img/brand/edwin.svg'),
(10,'Evisu','/img/brand/evisu.svg'),
(11,'Hackett','/img/brand/hackett.svg'),
(12,'Helly Hansen','/img/brand/helly.svg'),
(13,'Lacoste','/img/brand/lacoste.svg'),
(14,'Ligne Blanche','/img/brand/ligne-blanche.svg'),
(15,'maharishi','/img/brand/maharishi.svg'),
(16,'MARKET','/img/brand/market.svg'),
(17,'Master-piece','/img/brand/master-piece.svg'),
(18,'MA.Strum','/img/brand/mastrum.svg'),
(19,'Medicom Toy','/img/brand/medicom-toy.svg'),
(20,'MSGM','/img/brand/MSGM.svg'),
(21,'Napapijri','/img/brand/napapijri.svg'),
(22,'Native Union','/img/brand/native-union.svg'),
(23,'New Balance','/img/brand/new-balance.svg'),
(24,'Nike','/img/brand/nike.svg'),
(25,'Oakley','/img/brand/oakley.svg'),
(26,'Peaceful Hooligan','/img/brand/peaceful-hooligan.svg'),
(27,'Polo Ralph Lauren','/img/brand/polo-by-ralph-lauren.svg'),
(28,'Porter-Yoshida & Co','/img/brand/porter-yoshida.svg'),
(29,'Puma','/img/brand/puma.svg'),
(30,'Ray-Ban','/img/brand/ray-ban.svg'),
(31,'Reebok','/img/brand/reebok.svg'),
(32,'Ripndip','/img/brand/ripndip.svg'),
(33,'Sandqvist','/img/brand/sandqvist.svg'),
(34,'Stone Island','/img/brand/stone-island.svg'),
(35,'The North Face','/img/brand/the-north-face.svg'),
(36,'thisisneverthat','/img/brand/thisisneverthat.svg'),
(37,'Timberland','/img/brand/timberland.svg'),
(38,'Timex','/img/brand/timex.svg'),
(39,'Vans','/img/brand/vans.svg'),
(40,'Y-3','/img/brand/y-3.svg'),
(41,'YEEZY','/img/brand/yeezy.svg');