export const sale = {
	ul1: [
		{ to: '', text: 'Все бренды' },
		{ to: '', text: 'adidas Originals' },
		{ to: '', text: 'Alpha Indistries' },
		{ to: '', text: 'C.P. Company' },
		{ to: '', text: 'Calvin Klein Jeans' },
		{ to: '', text: 'Edwin' },
		{ to: '', text: 'Helly Hansen' },
		{ to: '', text: 'MARKET' },
		{ to: '', text: 'Napapijri' },
		{ to: '', text: 'New Balance' },
		{ to: '', text: 'Reebok' },
		{ to: '', text: 'thisisneverthat' },
		{ to: '', text: 'Vans' },
		{ to: '', text: 'YEEZY' },
	],
	ul2: [
		{ to: '', text: 'Все категории' },
		{ to: '', text: 'Кроссовки' },
		{ to: '', text: 'Куртки' },
		{ to: '', text: 'Толстовки' },
		{ to: '', text: 'Свитеры' },
		{ to: '', text: 'Рубашки' },
		{ to: '', text: 'Лонгсливы' },
		{ to: '', text: 'Футболки' },
		{ to: '', text: 'Брюки' },
		{ to: '', text: 'Наручные часы' },
		{ to: '', text: 'Шапки' },
		{ to: '', text: 'Кепки' },
		{ to: '', text: 'Носки' },
		{ to: '', text: 'Солнцезащитные очки' },
	],
	img: [
		{
			text: 'Аксессуары',
			img: '/img/header-menu/accessories.jpg',
		},
		{
			text: 'Женское',
			img: '/img/header-menu/women.jpg',
		},
		{
			text: 'Обувь',
			img: '/img/header-menu/shoes.jpg',
		},
		{
			text: 'Мужское',
			img: '/img/header-menu/men.jpg',
		},
	],
}
