export const man = {
	ul1: [
		{ to: '', text: 'Все бренды' },
		{ to: '', text: 'adidas Originals' },
		{ to: '', text: 'C.P. Company' },
		{ to: '', text: 'Comme des Garcons SHIRT' },
		{ to: '', text: 'Edwin' },
		{ to: '', text: 'Lacoste' },
		{ to: '', text: 'Levis' },
		{ to: '', text: 'Nike' },
		{ to: '', text: 'Polo Ralph Lauren' },
		{ to: '', text: 'Ripndip' },
		{ to: '', text: 'Stone Island' },
		{ to: '', text: 'The North Face' },
		{ to: '', text: 'thisisneverthat' },
		{ to: '', text: 'uniform experiment' },
	],
	ul2: [
		{ to: '', text: 'Все категории' },
		{ to: '', text: 'Кроссовки' },
		{ to: '', text: 'Ботинки' },
		{ to: '', text: 'Кеды' },
		{ to: '', text: 'Куртки' },
		{ to: '', text: 'Свитера' },
		{ to: '', text: 'Толстовки' },
		{ to: '', text: 'Рубашки' },
		{ to: '', text: 'Лонгсливы' },
		{ to: '', text: 'Поло' },
		{ to: '', text: 'Футболки' },
		{ to: '', text: 'Джинсы' },
		{ to: '', text: 'Брюки' },
		{ to: '', text: 'Шорты' },
	],
	img: [
		{
			text: 'Одежда',
			img: '/img/header-menu/mens_clothing.jpg',
		},
		{
			text: 'Обувь',
			img: '/img/header-menu/mens_footwear.jpg',
		},
	],
}
